# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- change-pipeline-3

variables:
  - group: semantic-release

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_12_x:
      node_version: 12.11.0

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

  env: 
    GIT_VAR: $(GH_TOKEN)
  
- script: echo $env:GIT_VAR

- script: > 
    npx semantic-release 
    -r https://github.com/romulo2franca/ocktops.git
    -b change-pipeline-3
  displayName: 'Semantic Release'