# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - group: semantic-release

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_12_x:
      node_version: 12.11.0

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: > 
    npx -p semantic-release
  env: 
    GH_TOKEN: $(GitHubToken)
  displayName: 'Semantic Release'